### ISSUE TITLE
What is 'ttsc'?

### ISSUE THREAD

**Issue by wjx0820** [egoist/hakka#6]
Could you explain what 'ttsc' means? Thanks!
![image](https://user-images.githubusercontent.com/31770433/103215230-bdc44c80-494d-11eb-9cfc-a7cdab3febc6.png)

**Comment by wjx0820** [comment]
I find out that is [ttypescript](https://www.npmjs.com/package/ttypescript)

**Comment by egoist** [comment]
yeah that's used for plugin support https://github.com/egoist/hakka/blob/ad560317d5983cbe457c743e7e61a54cf3813bdd/server/tsconfig.json#L21
